<html>
<!--

  Created using /
  Source can be edited via /otasu/2/edit

-->
<head>

    <meta charset=utf-8 />
    <title>JS Bin</title>

    <style type="text/css">
        article, aside, figure, footer, header, hgroup,
        menu, nav, section { display: block; }
    </style>
</head>
<body>
<p>
    <a id="fadeInLink" href="#">Div einblenden!</a>
</p>
    <form method="POST">
        <input id="textArray" type="text" value="NewName"/>
        <input id="SubmitButton" type="submit"/>
    </form>

<div id="box">
    <p>
        <a id="fadeOutLink" class="closeButton" href="#">X</a>
    </p>
    <p>
        <div id="className"/>
    </p>
</div>


<script>
    $(document).ready(function(){

        $("#fadeOutLink").click(function(){

            $("#box").fadeOut(2000);

            return false;

        });
        $("#fadeInLink").click(function(){

            $("#box").fadeIn(200);

            return false;
        });
        $("#SubmitButton").click(function(){

            var element = document.getElementById("className");

            element.innerHTML = document.getElementById("textArray").value;

            return false;

        });

    });

</script>
<!--
<script src="/js/render/edit.js"></script>
<script>var _gaq=[['_setAccount','UA-1656750-13'],['_trackPageview']];(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.src='//www.google-analytics.com/ga.js';s.parentNode.insertBefore(g,s)})(document,'script')</script></body>
-->
</html>