<!--
  User: phil
  Date: 20.06.12
 -->
<!--
<canvas id="myCanvas" width="400" height="400">
    Your browser does not support the canvas element.
</canvas>

<script type="text/javascript">
    $(document).ready(function() {

        var cycle = {draw: function() {
            var c=document.getElementById("myCanvas");
            var ctx=c.getContext("2d");
            ctx.fillStyle="#FF0000";
            ctx.beginPath();
            ctx.arc(200,150,50,0,Math.PI*2,true);
            ctx.closePath();
            ctx.fill();
            ctx.drag
        }};
        cycle.draw();
    });
</script>
-->

<script src="http://www.html5canvastutorials.com/libraries/kinetic-v3.10.0.js"></script>

<style>
    body {
        margin: 0px;
        padding: 0px;
    }
    canvas {
        border: 1px solid #9C9898;
    }
</style>

<script>
    window.onload = function() {
        var stage = new Kinetic.Stage({
            container: "container",
            width: 600,
            height: 300
        });
        var layer = new Kinetic.Layer();
        var rectX = stage.getWidth() / 2 - 50;
        var rectY = stage.getHeight() / 2 - 50;

        var box = new Kinetic.Rect({
            x: rectX,
            y: rectY,
            width: 100,
            height: 100,
            fill: "green",
            stroke: "black",
            strokeWidth: 1,
            draggable: true
        });

        // add cursor styling
        box.on("mouseover", function() {
            document.body.style.cursor = "pointer";
        });
        box.on("mouseout", function() {
            document.body.style.cursor = "default";
        });

        layer.add(box);

        var circle = new Kinetic.Circle({
            x: stage.getWidth() / 2,
            y: stage.getHeight() / 2,
            radius: 20,
            fill: "red",
            stroke: "black",
            strokeWidth: 1,
            draggable: true
        });

        // add cursor styling
        circle.on("mouseover", function() {
            document.body.style.cursor = "pointer";
        });
        circle.on("mouseout", function() {
            document.body.style.cursor = "default";
        });

        layer.add(circle);
        stage.add(layer);

    };

</script>
<div id="container"></div>