<!--
  User: pascal
  Date: 06.05.12
 -->
<div id="loading">
    <div id="title">Welcome <?=$this->username?></div>
    <div>
        <div id="loading_0" class="active"></div>
        <div id="loading_1"></div>
        <div id="loading_2"></div>
        <div id="loading_3"></div>
    </div>
</div>

<!-- Dummy so we can redirect to main site -->
<a href="load/nextsite" id="nextSite"></a>

<script type="text/javascript">
    $(document).ready(function() {
        IndexController.loadingAction();
    });
    nextSite = document.getElementById('nextSite');
    setTimeout("nextSite.click()",3000);
</script>