<!--
  User: Tobi
  Date: 24.10.2012
 -->

<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            margin: 1px;
            padding: 1px;
        }
        canvas {
            border: 1px solid #c3c3c3;
        }
    </style>
    <script>
        //variable for the sum of Nodes - is on 2 because of 2 standard nodes already existing

        var markedNode;
        var markedNodeFillBackup;

        //Function for Mouse Location
        function writeMessage(messageLayer, message) {
            var context = messageLayer.getContext();
            messageLayer.clear();
            context.font = '18pt Calibri';
            context.fillStyle = 'black';
            context.fillText(message, 10, 25);
            context.fillText(sumOfNodes, 250, 25);
        }


        // Marks nodes and saves fill color
        function clickNode(node, layer) {
            markedNode.fillBackground(markedNodeFillBackup);
            markedNode.hideAnchors();
            if(markedNode.childElements.length != 0 && markedNode.areThereHiddenChildren == false){
                markedNode.newHideButton.hide();
            }
            //markedNode.shape.setFill(markedNodeFillBackup);
            markedNode = node;
            markedNodeFillBackup = markedNode.getBackground();//markedNode.shape.getFill();
            markedNode.fillBackground('3D9DB3');
            markedNode.showAnchors();
            if(markedNode.childElements.length != 0 && markedNode.areThereHiddenChildren == false){
                markedNode.newHideButton.show();
            }
            //markedNode.shape.setFill('green');

            layer.draw();
        }

        //onload function
        window.onload = function() {
            var stage = new Kinetic.Stage({
                container: "container",
                width: 1024,
                height: 768
            });


            //Layer for shapes
            var layer = new Kinetic.Layer();
            // MessageLayer for Mouseposition and other debug notes
            var messageLayer = new Kinetic.Layer();


            // Oval Shape 1
            var base = new newNodeFactory.createBaseNode(stage, layer);

            markedNode = base;
            markedNodeFillBackup = base.getBackground();
            markedNode.fillBackground('3D9DB3');


            //Oval Shape 2
            var oval2 = new newNodeFactory.newEllipseNode(layer, base);


            //Button for showing the marked node
            //this functionality would be used later for hide/minimize (and reshow) parts of the mindmap
            var newShowButton = debugGUI.buildNewShowButton();
            newShowButton.on("click", function(){
                markedNode.showChildren(layer);
            });
            layer.add(newShowButton);

            //Button for hiding the marked node
            //this functionality would be used later for hide/minimize parts of the mindmap
            var newHideButton = debugGUI.buildNewHideButton();
            newHideButton.on("click", function(){
                markedNode.hideChildren(layer);
            });
            layer.add(newHideButton);

            //Button for FactoryMethod of creating new Nodes
            var newEllipseButton = debugGUI.buildNewEllipseButton();
            newEllipseButton.on("click", function(){
                new newNodeFactory.newEllipseNode(layer, markedNode);
            });
            layer.add(newEllipseButton);

            var newRectButton = debugGUI.buildNewRectButton();
            newRectButton.on("click", function(){
                new newNodeFactory.newRectNode(layer, markedNode);
            });
            layer.add(newRectButton);

            var newEditTextButton = debugGUI.buildNewEditTextButton();
            newEditTextButton.on("click", function(){
                var newText=prompt("Please enter a new name", markedNode.getText());
                if (newText !=null )
                {
                    markedNode.setText(newText);
                }
            });
            layer.add(newEditTextButton);


            //function for mouse coordinates on shape - only for debugging and development
            stage.on("mousemove", function() {
                var mousePos = stage.getMousePosition();
                writeMessage(messageLayer, 'x: ' + mousePos.x + ', y: ' + mousePos.y);
            });


            // add the layer to the stage
            stage.add(layer);
            stage.add(messageLayer);
        };

    </script>

            <Welcome <?=$this->username?>,<br>
            <a href="login/logout" >Click here to logout</a>

</head>
<body>

    <div id="container"></div>
    <div align="center" >Copyright © Open Your Mind 2012-2013</div>
</body>
</html>