<!--
  User: sebastian
  Date: 26.10.12
 -->
<div class="container">
    <header>
        <h1>Login or Registration to <span>Open Your Mind</span></h1>
    </header>
    <section>
        <div id="container_demo" >
            <!-- hidden anchor to stop jump http://www.css3create.com/Astuce-Empecher-le-scroll-avec-l-utilisation-de-target#wrap4  -->
            <a class="hiddenanchor" id="toregister"></a>
            <a class="hiddenanchor" id="tologin"></a>

            <div id="wrapper">

                <div id="login" class="animate form">

                    <form  action="aNonExistentScript.php" autocomplete="on">
                        <h1>Log in</h1>
                        <p class="change_link">
                            Not a member yet ?
                            <a href="#toregister" class="to_register">Join</a><a href="#to_try" class="to_try">Try it out (not working)</a>
                        </p>
                        <p>
                            <label for="username" class="uname" data-icon="u" > Your email or username </label>
                            <input id="username" name="username" required="required" type="text" placeholder="myusername or myemail@mail.com"/>
                        </p>
                        <p>
                            <label for="password" class="youpasswd" data-icon="p"> Your password </label>
                            <input id="password" name="password" required="required" type="password" placeholder="eg. 123456" />
                        </p>
                        <p class="keeplogin">
                            <input type="checkbox" name="loginkeeping" id="loginkeeping" value="loginkeeping" />
                            <label for="loginkeeping">Keep me logged in</label>
                        </p>
                        <p class="login button">
                            <input type="submit" value="Login" />
                        </p>
                        <div class="uvFieldEtc uvFieldEtc-providers">
                            <span class="uvFieldEtcLabel">or sign in with (not working)</span>
                            <a data-provider="facebook"><a href="" tabindex="0" title="Sign in via Facebook"><img class="favicon" src="../www/images/fb.png" alt="facebook"></a></a>
                            <a data-provider="google"><a href="" tabindex="0" title="Sign in via Google"><img class="favicon" src="../www/images/gp.png" alt="google"></a></a>
                        </div>

                    </form>
                </div>

                <div id="register" class="animate form">
                    <form  action="aNonExistentScript.php" autocomplete="on">
                        <h1> Sign up </h1>
                        <p class="change_link">
                            Already a member ?
                            <a href="#tologin" class="to_register"> Go and log in </a>
                        </p>
                        <p>
                            <label for="usernamesignup" class="uname" data-icon="u">Your username</label>
                            <input id="usernamesignup" name="usernamesignup" required="required" type="text" placeholder="username" />
                        </p>
                        <p>
                            <label for="emailsignup" class="youmail" data-icon="e" > Your email</label>
                            <input id="emailsignup" name="emailsignup" required="required" placeholder="myemail@email.com"/>
                        </p>
                        <p>
                            <label for="passwordsignup" class="youpasswd" data-icon="p">Your password </label>
                            <input id="passwordsignup" name="passwordsignup" required="required" type="password" placeholder="eg. 123456"/>
                        </p>
                        <p>
                            <label for="passwordsignup_confirm" class="youpasswd" data-icon="p">Please confirm your password </label>
                            <input id="passwordsignup_confirm" name="passwordsignup_confirm" required="required" type="password" placeholder="eg. 123456"/>
                        </p>
                        <p class="signin button">
                            <input type="submit" value="Sign up"/>
                        </p>
                    </form>
                </div>

            </div>
        </div>
    </section>
</div>