<!--
  User: sebastian
  Date: 26.10.12
 -->
<div class="container">
    <header>
        <h1>Open Your Mind</h1>
    </header>
    <section>
        <div id="container_demo" >
            <!-- hidden anchor to stop jump -->
            <a class="hiddenanchor" id="toregister"></a>
            <a class="hiddenanchor" id="tologin"></a>

            <div id="wrapper">

                <div id="login" class="animate form">

                    <form  action="login/login" autocomplete="on" method="post">
                        <h1>Log in</h1>
                        <p class="change_link">
                            Not a member yet ?
                            <a href="#toregister" class="to_register">Sign up</a>
                             or
                            <a href="login/tryout">Try it out</a>
                        </p>
                        <?php if(isset($this->errorMessage)){ ?>
                            <p class="error">
                                <?
                                    echo $this->errorMessage;
                                    unset($this->errorMessage);
                                ?>
                            </p>
                        <?php } ?>
                        <p>
                            <label for="username" class="uname" data-icon="u" > Your email or username </label>
                            <input id="username" name="username" required="required" type="text" placeholder="myusername or myemail@mail.com"/>
                        </p>
                        <p>
                            <label for="password" class="youpasswd" data-icon="p"> Your password </label>
                            <input id="password" name="password" required="required" type="password" placeholder="eg. 123456" />
                        </p>
                        <p class="login button">
                            <input type="submit" />
                        </p>
                        <div>
                            <span>or sign in with </span>
                            <a data-provider="facebook"><a href="login/tryout" tabindex="0" title="Sign in via Facebook"><img class="favicon" src="<?=$this->baseUrl('../www/images/fb.png')?>" alt="facebook"></a></a>
                        </div>
                    </form>
                </div>

                <div id="register" class="animate form">
                    <form  action="login/signup" autocomplete="on" method="post">
                        <h1> Sign up </h1>
                        <p class="change_link">
                            Already a member ?
                            <a href="#tologin" class="to_register"> Go and log in </a>
                        </p>
                        <?php if(isset($this->errorMessage)){ ?>
                        <p class="error">
                            <?php
                                echo $this->errorMessage;
                                unset($this->errorMessage);
                            ?>
                        </p>
                        <?php } ?>
                        <p>
                            <label for="usernamesignup" class="uname" data-icon="u">Your username</label>
                            <input id="usernamesignup" name="usernamesignup" required="required" type="text" placeholder="username" />
                        </p>
                        <p>
                            <label for="emailsignup" class="youmail" data-icon="e" > Your email</label>
                            <input id="emailsignup" name="emailsignup" required="required" type="email" placeholder="myemail@email.com"/>
                        </p>
                        <p>
                            <label for="passwordsignup" class="youpasswd" data-icon="p">Your password </label>
                            <input id="passwordsignup" name="passwordsignup" required="required" type="password" placeholder="eg. 123456"/>
                        </p>
                        <p>
                            <label for="passwordsignup_confirm" class="youpasswd" data-icon="p">Please confirm your password </label>
                            <input id="passwordsignup_confirm" name="passwordsignup_confirm" required="required" type="password" placeholder="eg. 123456"/>
                        </p>
                        <p class="signin button">
                            <input type="submit" value="Sign up"/>
                        </p>
                        <div>
                            <span>or sign in with </span>
                            <a data-provider="facebook"><a href="login/tryout" tabindex="0" title="Sign in via Facebook"><img class="favicon" src="<?=$this->baseUrl('../www/images/fb.png')?>" alt="facebook"></a></a>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </section>
    <footer>

    </footer>
</div>