<!--
  User: pascal
  Date: 06.05.12
 -->
<?php echo $this->doctype() ?>
<html>
<head>

    <?php echo $this->headTitle() ?>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php
        $css = scandir(BASE_PATH . '/www/css');
        foreach($css as $value) {
            if(1 == substr_count($value, '.css'))
                echo '<link rel="stylesheet" type="text/css" href="' . $this->baseUrl('/../www/css/'. $value ) .'">';
        }

        $js = scandir(BASE_PATH . '/www/js');
        foreach($js as $value) {
            if(1 == substr_count($value, '.js'))
                echo '<script type="text/javascript" src="' . $this->baseUrl('/../www/js/'. $value ) .'"></script>';
        }
    ?>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
</head>
<body>
<header><?php echo $this->action('index', 'menu'); ?></header>
<div id="content"><?php echo $this->layout()->content ?></div>
<footer><?php echo $this->layout()->footer ?></footer>
</body>
</html>